// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBha16q-ZL0ST-FLddz063y-gvWIMt9804',
    appId: '1:617308868736:web:f9ff28ac6e4e10437fd665',
    messagingSenderId: '617308868736',
    projectId: 'car-15782',
    authDomain: 'car-15782.firebaseapp.com',
    databaseURL: 'https://car-15782-default-rtdb.firebaseio.com',
    storageBucket: 'car-15782.firebasestorage.app',
    measurementId: 'G-ZRQ3KS1886',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDucZedkqsJsyhW9xm_Q5lYLm45SlVwGh4',
    appId: '1:617308868736:android:c1cd6d3402d7ec937fd665',
    messagingSenderId: '617308868736',
    projectId: 'car-15782',
    databaseURL: 'https://car-15782-default-rtdb.firebaseio.com',
    storageBucket: 'car-15782.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO4agigtgd6Noy54jQkSLvnRRWSRBfSUI',
    appId: '1:617308868736:ios:5e519676e88cd50c7fd665',
    messagingSenderId: '617308868736',
    projectId: 'car-15782',
    databaseURL: 'https://car-15782-default-rtdb.firebaseio.com',
    storageBucket: 'car-15782.firebasestorage.app',
    iosBundleId: 'com.example.usersApp.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO4agigtgd6Noy54jQkSLvnRRWSRBfSUI',
    appId: '1:617308868736:ios:70cc7d738cdf46c97fd665',
    messagingSenderId: '617308868736',
    projectId: 'car-15782',
    databaseURL: 'https://car-15782-default-rtdb.firebaseio.com',
    storageBucket: 'car-15782.firebasestorage.app',
    iosBundleId: 'com.example.usersApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBha16q-ZL0ST-FLddz063y-gvWIMt9804',
    appId: '1:617308868736:web:f7640a3c09b907d17fd665',
    messagingSenderId: '617308868736',
    projectId: 'car-15782',
    authDomain: 'car-15782.firebaseapp.com',
    databaseURL: 'https://car-15782-default-rtdb.firebaseio.com',
    storageBucket: 'car-15782.firebasestorage.app',
    measurementId: 'G-BPC6JNEDXE',
  );

}